### ISSUE TITLE
install documents need detailing 

### ISSUE THREAD

**Issue by wang415** [devsapp/start-fc-kodbox#3]
需要更新部署文档 我是没有部署成功
:/home/wade/Code/start-fc-kodbox# s init start-fc-kodbox -d start-fc-kodbox

🚀  Serverless Awesome: https://github.com/Serverless-Devs/Serverless-Devs/blob/master/docs/zh/awesome.md

✖ Message:

ERROR:

this.breakLines(...).flat is not a function

TraceId:     cc15310bfbc61647794887288
Environment: @serverless-devs/s: 2.0.101, s-home: /root/.s, linux-x64, node-v10.19.0
Documents:   https://www.serverless-devs.com
Discussions: https://github.com/Serverless-Devs/Serverless-Devs/discussions
Issues:      https://github.com/Serverless-Devs/Serverless-Devs/issues

Please copy traceId: cc15310bfbc61647794887288 and join Dingding group: 33947367 for consultation.
You can run 's clean --all' to clean Serverless devs.

**Comment by heimanba** [comment]
serverless-devs cli底层的一个依赖包更新导致，已经锁住版本，下个版本发布
